#define SALLE_TYPE_VIDE 0
#define SALLE_TYPE_EAU 1
#define SALLE_TYPE_NOURRITURE 2
#define SALLE_TYPE_REINE 3

#define FOURMIS_ACTION_DEPLACEMENT 0
#define FOURMIS_ACTION_RAMASSE_NOURRITURE 1
#define FOURMIS_ACTION_COMMENCE_CONSTRUCTION 2
#define FOURMIS_ACTION_TERMINE_CONSTRUCTION 3
#define FOURMIS_ACTION_ATTAQUE 4
#define FOURMIS_ACTION_ATTAQUE_TUNNEL 5
#define FOURMIS_ACTION_FOURMI_PASSE 6

#define REINE_ACTION_CREER_FOURMI 0
#define REINE_ACTION_ENVOYER_FOURMI 1
#define REINE_ACTION_RECUPERER_FOURMI 2
#define REINE_ACTION_AMELIORE_STOCKAGE 3
#define REINE_ACTION_AMELIORE_PRODUCTION 4
#define REINE_ACTION_AMELIORE_ENVOI 5
#define REINE_ACTION_AMELIORE_VITESSE_AMELIORATION 6
#define REINE_ACTION_AMELIORE_RAMASSAGE 7
#define REINE_ACTION_AMELIORE_VIE 8
#define REINE_ACTION_AMELIORE_EAU 9
#define REINE_ACTION_AMELIORE_DEGATS 10
#define REINE_ACTION_REINE_PASSE 11